### ISSUE TITLE
Question about the function-get_fs_net_scale

### ISSUE THREAD

**Issue by Eddieeee-Liu** [lolrudy/RBP_Pose#1]
Dear author:

Thanks for your great work. I am a little bit confused with the function, "get_fs_net_scale", which is used in the data loader. 
The original code is shown bellow:

        # model pc x 3
        lx = 2 * max(max(model[:, 0]), -min(model[:, 0]))
        ly = max(model[:, 1]) - min(model[:, 1])
        lz = max(model[:, 2]) - min(model[:, 2])
        # real scale
        lx_t = lx * nocs_scale * 1000
        ly_t = ly * nocs_scale * 1000
        lz_t = lz * nocs_scale * 1000

I have 2 questions:
     (1) Why lx is calculated in an different manner, I have checked the code of GPV_Pose where lx = max(model[:, 0]) - min(model[:, 0])
     (2) I think the 3D model is already in the NOCS space, why do we multiply lx by nocs_scale?

**Comment by lolrudy** [comment]
(1) Following SPD, the center of 'mug' category is moved to the center the origin of the object coordinate frame is on the axis of symmetry. The size on x-axis should be changed accordingly and the calculation should be different from the other two axises. 
(2) nocs_scale is generated by the scripts from SPD. Its meaning is the scale ratio between the real scale and the NOCS scale. lx, ly, lz are computed in NOCS space, and lx_t, ly_t, lz_t are the real size.

**Comment by Eddieeee-Liu** [comment]
> (1) Following SPD, the center of 'mug' category is moved to the center the origin of the object coordinate frame is on the axis of symmetry. The size on x-axis should be changed accordingly and the calculation should be different from the other two axises. (2) nocs_scale is generated by the scripts from SPD. Its meaning is the scale ratio between the real scale and the NOCS scale. lx, ly, lz are computed in NOCS space, and lx_t, ly_t, lz_t are the real size.

#original code
fsnet_scale_delta, mean_shape = self.get_fs_net_scale(self.id2cat_name[str(cat_id + 1)], model, nocs_scale)
        fsnet_scale_delta = fsnet_scale_delta / 1000.0
#

Thanks for your reponse, I still wonder why fsnet_scale_delta does not need to be divided by nocs_scale, because we need to use it later to calculate the distance from the nocs_coords of pred. I guess it should be converted to nocs space by nocs_scale?

**Comment by lolrudy** [comment]
This scale_delta is the ground truth label of the pose head. The final scale prediction is recovered by
scale = scale_delta + mean_shape
You can find the details in FS-Net.

**Comment by Eddieeee-Liu** [comment]
> This scale_delta is the ground truth label of the pose head. The final scale prediction is recovered by scale = scale_delta + mean_shape You can find the details in FS-Net.

Thanks
