### ISSUE TITLE
Question: the training epoch of the second stage

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [lolrudy/RBP_Pose#4]
Hi, thanks for sharing the code. 

I am wondering how many epochs should be used for training in the second stage. Is it still `150`? 

By the way, is there any schedule for the release of the trained weights?

**Comment by lolrudy** [comment]
Sorry for waiting. I upload the trained weights just now. We use 150 epochs previously, but more epochs (200-300 maybe?) might yield better results.

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks!
