### ISSUE TITLE
How to install nn-distance==0.0.0 and GuideConv==0.0.0 in requirements.txt?

### ISSUE THREAD

**Issue by JiahaoSun0514** [lolrudy/RBP_Pose#6]
Thanks for the code sharing and the impressive work.

I install nn-distance==0.0.0 and GuideConv==0.0.0 in requirements.txt. Errors occur with or without "==0.0.0". 

ERROR: Could not find a version that satisfies the requirement nn-distance
ERROR: No matching distribution found for nn-distance

Thank you so much!

**Comment by JiahaoSun0514** [comment]
Sorry to bother you. May you reply to me at your convenience? Thanks.

**Comment by lolrudy** [comment]
nn-distance is in prepare_data/lib/nn_distance. Run "python setup.py install" to install it.
GuideConv is not needed in the final version.  If you still want to install it, go to network/backbone_repo/Resnet/exts and run "python setup.py install".

**Comment by JiahaoSun0514** [comment]
> nn-distance is in prepare_data/lib/nn_distance. Run "python setup.py install" to install it. GuideConv is not needed in the final version. If you still want to install it, go to network/backbone_repo/Resnet/exts and run "python setup.py install".

Thanks for your reply.
