### ISSUE TITLE
How to generate 'Real/train/mug_handle.pkl' and 'results/mean_shape/mean_points_emb.npy' ?

### ISSUE THREAD

**Issue by DHuiTnut** [lolrudy/RBP_Pose#9]
Hi, I am interested in your excellent work and i tried to reproduce your results. 

Could you tell me how to generate ['Real/train/mug_handle.pkl'](https://github.com/lolrudy/RBP_Pose/blob/adf074149543554cc987923415e7c0e9ad10ed71/datasets/load_data_selfsketchpose.py#L189C91-L189C91) and 'results/mean_shape/mean_points_emb.npy' ?

Thanks.

**Comment by lolrudy** [comment]
mug_handle.pkl records whether the mug handle is visible in each training image.  It is annotated manually. The file is uploaded in https://github.com/lolrudy/GPV_Pose
mean_points_emb.npy is the output file of SPD. You can generate it following https://github.com/mentian/object-deformnet

**Comment by DHuiTnut** [comment]
Thanks! It helps me a lot.
